-- 创建alipay_wap_pay_records表，用于存储alipay.trade.wap.pay接口返回的字段
-- 并添加file_id字段关联file_info表

CREATE TABLE alipay_wap_pay_records (
    -- 主键字段
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    
    -- 支付宝接口返回的基本公共参数
    code VARCHAR2(20) NOT NULL, -- 接口调用结果码
    msg VARCHAR2(100) NOT NULL, -- 接口调用结果描述
    sub_code VARCHAR2(32), -- 业务错误码
    sub_msg VARCHAR2(100), -- 业务错误描述
    
    -- 支付宝接口返回的业务参数
    trade_no VARCHAR2(64) NOT NULL, -- 支付宝交易号
    out_trade_no VARCHAR2(64) NOT NULL, -- 商户订单号
    buyer_id VARCHAR2(32) NOT NULL, -- 买家支付宝用户ID
    buyer_logon_id VARCHAR2(100) NOT NULL, -- 买家支付宝账号
    seller_id VARCHAR2(32) NOT NULL, -- 卖家支付宝用户ID
    seller_email VARCHAR2(100), -- 卖家支付宝账号
    total_amount NUMBER(11,2) NOT NULL, -- 订单总金额（元）
    receipt_amount NUMBER(11,2), -- 实收金额（元）
    invoice_amount NUMBER(11,2), -- 开票金额（元）
    buyer_pay_amount NUMBER(11,2), -- 买家实付金额（元）
    point_amount NUMBER(11,2), -- 积分抵扣金额（元）
    refund_fee NUMBER(11,2), -- 退款金额（元）
    subject VARCHAR2(256) NOT NULL, -- 订单标题
    body VARCHAR2(1024), -- 订单描述
    gmt_create DATE NOT NULL, -- 交易创建时间
    gmt_payment DATE, -- 交易付款时间
    gmt_refund DATE, -- 交易退款时间
    gmt_close DATE, -- 交易结束时间
    
    -- 关联file_info表的字段
    file_id VARCHAR2(18) NOT NULL, -- 关联file_info表的file_id
    
    -- 系统字段
    create_time DATE DEFAULT SYSDATE NOT NULL, -- 记录创建时间
    update_time DATE DEFAULT SYSDATE NOT NULL, -- 记录更新时间
    
    -- 主键约束
    CONSTRAINT pk_alipay_wap_pay_records PRIMARY KEY (record_id),
    
    -- 唯一约束
    CONSTRAINT uk_alipay_wap_pay_trade_no UNIQUE (trade_no),
    CONSTRAINT uk_alipay_wap_pay_out_trade_no UNIQUE (out_trade_no),
    
    -- 外键约束，关联file_info表
    CONSTRAINT fk_alipay_wap_pay_file_id FOREIGN KEY (file_id) REFERENCES file_info(file_id) ON DELETE CASCADE,
    
    -- 检查约束
    CONSTRAINT ck_alipay_wap_pay_total_amount CHECK (total_amount >= 0),
    CONSTRAINT ck_alipay_wap_pay_receipt_amount CHECK (receipt_amount >= 0 OR receipt_amount IS NULL),
    CONSTRAINT ck_alipay_wap_pay_invoice_amount CHECK (invoice_amount >= 0 OR invoice_amount IS NULL),
    CONSTRAINT ck_alipay_wap_pay_buyer_pay_amount CHECK (buyer_pay_amount >= 0 OR buyer_pay_amount IS NULL),
    CONSTRAINT ck_alipay_wap_pay_point_amount CHECK (point_amount >= 0 OR point_amount IS NULL),
    CONSTRAINT ck_alipay_wap_pay_refund_fee CHECK (refund_fee >= 0 OR refund_fee IS NULL)
);

-- 提交事务
COMMIT;

-- 输出创建成功信息
SELECT 'alipay_wap_pay_records表创建成功' AS message FROM DUAL;