-- 创建支付配置表，用于存储支付相关的配置信息
-- 价格类型：1-便宜，2-昂贵，3-其他
-- 金额字段：存储具体的支付金额
-- URL字段：存放支付页面的URL地址

CREATE TABLE payment_config (
    -- 主键字段
    config_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    
    -- 价格类型字段，1位字符，取值为1-便宜，2-昂贵，3-其他
    price_type CHAR(1) NOT NULL,
    
    -- 金额字段，存储具体的支付金额，最多11位数字，2位小数
    amount NUMBER(11,2) NOT NULL,
    
    -- URL地址字段，存放跳转到mobile_payment_simple.html的URL地址
    payment_url VARCHAR2(200) NOT NULL,
    
    -- 描述字段，可选，用于说明配置的具体用途
    description VARCHAR2(200),
    
    -- 状态字段，用于标记配置是否启用，Y-启用，N-禁用
    status CHAR(1) DEFAULT 'Y' NOT NULL,
    
    -- 系统字段
    create_time DATE DEFAULT SYSDATE NOT NULL,
    update_time DATE DEFAULT SYSDATE NOT NULL,
    
    -- 主键约束
    CONSTRAINT pk_payment_config PRIMARY KEY (config_id),
    
    -- 检查约束，确保价格类型只能是1、2或3
    CONSTRAINT ck_payment_config_price_type CHECK (price_type IN ('1', '2', '3')),
    
    -- 检查约束，确保金额大于等于0
    CONSTRAINT ck_payment_config_amount CHECK (amount >= 0),
    
    -- 检查约束，确保状态只能是Y或N
    CONSTRAINT ck_payment_config_status CHECK (status IN ('Y', 'N'))
);

-- 添加索引，提高查询效率
CREATE INDEX idx_payment_config_status ON payment_config(status);

-- 初始化数据
INSERT INTO payment_config (price_type, amount, payment_url, description, status)
VALUES ('1', 3.00, 'http://192.168.100.174:5000/mobile_payment_simple', '学习资料购买默认支付配置', 'Y');

-- 提交事务
COMMIT;

-- 输出创建成功信息
SELECT 'payment_config表创建成功，初始数据已插入' AS message FROM DUAL;