#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
验证payment_config表是否存在，并在必要时重新创建
"""

import os
import sys

# 添加当前目录到系统路径
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

try:
    import cx_Oracle
    print("已导入cx_Oracle模块")
except ImportError:
    print("错误：未安装cx_Oracle模块")
    print("请使用以下命令安装：pip install cx_Oracle")
    sys.exit(1)

# 数据库连接配置
DB_CONFIG = {
    'user': 'system',               # 数据库用户名
    'password': 'oracle123',        # 数据库密码
    'dsn': 'localhost:1521/ORCLM',   # 数据库连接字符串
    'encoding': 'UTF-8'             # 字符编码
}

def check_table_exists():
    """
    检查payment_config表是否存在
    
    Returns:
        bool: 表存在返回True，否则返回False
    """
    try:
        # 连接数据库
        connection = cx_Oracle.connect(**DB_CONFIG)
        cursor = connection.cursor()
        
        # 查询表是否存在
        query = "SELECT table_name FROM user_tables WHERE table_name = 'PAYMENT_CONFIG'"
        cursor.execute(query)
        result = cursor.fetchone()
        
        # 关闭游标和连接
        cursor.close()
        connection.close()
        
        return result is not None
    except Exception as e:
        print(f"检查表是否存在时出错: {str(e)}")
        return False

def create_table():
    """
    创建payment_config表
    
    Returns:
        bool: 创建成功返回True，否则返回False
    """
    try:
        # 连接数据库
        connection = cx_Oracle.connect(**DB_CONFIG)
        cursor = connection.cursor()
        
        # 创建表
        create_table_sql = """
        CREATE TABLE payment_config (
            -- 主键字段
            price_id NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
            
            -- 价格类型字段，1位字符，取值为1-便宜，2-昂贵，3-其他
            price_type CHAR(1) NOT NULL,
            
            -- 金额字段，存储具体的支付金额，最多11位数字，2位小数
            amount NUMBER(11,2) NOT NULL,
            
            -- URL地址字段，存放跳转到mobile_payment_simple.html的URL地址
            payment_url VARCHAR2(200) NOT NULL,
            
            -- 描述字段，可选，用于说明配置的具体用途
            description VARCHAR2(200),
            
            -- 状态字段，用于标记配置是否启用，Y-启用，N-禁用
            status CHAR(1) DEFAULT 'Y' NOT NULL,
            
            -- 系统字段
            create_time DATE DEFAULT SYSDATE NOT NULL,
            update_time DATE DEFAULT SYSDATE NOT NULL,
            
            -- 主键约束
            CONSTRAINT pk_payment_config PRIMARY KEY (price_id),
            
            -- 检查约束，确保价格类型只能是1、2或3
            CONSTRAINT ck_payment_config_price_type CHECK (price_type IN ('1', '2', '3')),
            
            -- 检查约束，确保金额大于等于0
            CONSTRAINT ck_payment_config_amount CHECK (amount >= 0),
            
            -- 检查约束，确保状态只能是Y或N
            CONSTRAINT ck_payment_config_status CHECK (status IN ('Y', 'N'))
        )
        """
        
        cursor.execute(create_table_sql)
        
        # 添加索引
        create_index_sql = "CREATE INDEX idx_payment_config_status ON payment_config(status)"
        cursor.execute(create_index_sql)
        
        # 插入初始数据
        insert_data_sql = """
        INSERT INTO payment_config (price_type, amount, payment_url, description, status)
        VALUES ('1', 3.00, 'http://192.168.100.174:5000/mobile_payment_simple', '学习资料购买默认支付配置', 'Y')
        """
        cursor.execute(insert_data_sql)
        
        # 提交事务
        connection.commit()
        
        # 关闭游标和连接
        cursor.close()
        connection.close()
        
        print("payment_config表创建成功，初始数据已插入")
        return True
    except Exception as e:
        print(f"创建表时出错: {str(e)}")
        return False

def main():
    """
    主函数
    """
    print("验证payment_config表是否存在...")
    
    if check_table_exists():
        print("payment_config表已存在")
    else:
        print("payment_config表不存在，开始创建...")
        if create_table():
            print("表创建成功")
        else:
            print("表创建失败")
    
    # 列出所有表，供用户参考
    print("\n当前用户下的所有表:")
    try:
        connection = cx_Oracle.connect(**DB_CONFIG)
        cursor = connection.cursor()
        cursor.execute("SELECT table_name FROM user_tables ORDER BY table_name")
        tables = cursor.fetchall()
        for table in tables:
            print(f"  - {table[0]}")
        cursor.close()
        connection.close()
    except Exception as e:
        print(f"查询表列表时出错: {str(e)}")

if __name__ == '__main__':
    main()